document.write("<meta charset=\"utf-8\">");
document.write("<title>Virtual Banking System</title>");
document.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");    
document.write("<meta name=\"description\" content=\"Virtual Banking System\">");        
document.write("<meta name=\"author\" content=\"Capbility Center for chinasoft\">");       
document.write("<link  href=\""+contextPath+"/css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">");
document.write("<link href=\""+contextPath+"/css/charisma-app.css\" rel=\"stylesheet\">");        
document.write("<link href=\""+contextPath+"/bower_components/fullcalendar/dist/fullcalendar.css\" rel=\"stylesheet\">"); 		
document.write("<link href=\""+contextPath+"/bower_components/fullcalendar/dist/fullcalendar.print.css\" rel=\"stylesheet\" media=\"print\">"); 
document.write("<link href=\""+contextPath+"/bower_components/chosen/chosen.min.css\" rel=\"stylesheet\">"); 
document.write("<link href=\""+contextPath+"/bower_components/colorbox/example3/colorbox.css\" rel=\"stylesheet\">"); 
document.write("<link href=\""+contextPath+"/bower_components/responsive-tables/responsive-tables.css\" rel=\"stylesheet\">"); 
document.write("<link href=\""+contextPath+"/bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css\" rel=\"stylesheet\">");                         
document.write("<link href=\""+contextPath+"/css/jquery.noty.css\" rel=\"stylesheet\">");                         
document.write("<link href=\""+contextPath+"/css/noty_theme_default.css\" rel=\"stylesheet\">"); 
document.write("<link href=\""+contextPath+"/css/elfinder.min.css\" rel=\"stylesheet\">");                          
document.write("<link href=\""+contextPath+"/css/elfinder.theme.css\" rel=\"stylesheet\">");                            
document.write("<link href=\""+contextPath+"/css/jquery.iphone.toggle.css\" rel=\"stylesheet\">");                          
document.write("<link href=\""+contextPath+"/css/uploadify.css\" rel=\"stylesheet\">");                                
document.write("<link href=\""+contextPath+"/css/animate.min.css\" rel=\"stylesheet\">");                               
document.write("<script src=\""+contextPath+"/bower_components/jquery/jquery.min.js\"></script>");  
//<!-- The fav icon -->
document.write("<link rel=\"shortcut icon\" href=\""+contextPath+"/img/favicon1.ico>"); 
document.write("");