document.write("<div class=\"col-sm-2 col-lg-2\">");
document.write("	<div class=\"sidebar-nav\">");        
document.write("		<div class=\"nav-canvas\">"); 		
document.write("			<div class=\"nav-sm nav nav-stacked\"></div>"); 
document.write(" 			<ul class=\"nav nav-pills nav-stacked main-menu\">"); 
document.write(" 				<li class=\"nav-header\">Main</li>"); 
document.write(" 				<li><a class=\"ajax-link\" href=\""+contextPath+"/index.html\"><i class=\"glyphicon glyphicon-home\"></i><span> index</span></a></li>"); 
document.write(" 				<li class=\"accordion\"><a href=\"#\"><i class=\"glyphicon glyphicon-plus\"></i><span>Account</span></a>");                         
document.write(" 	 				<ul class=\"nav nav-pills nav-stacked\">");                         
document.write(" 	 					<li><a href=\""+contextPath+"/account/Creation.html\">Creation</a></li>"); 
document.write(" 	 					<li><a href=\""+contextPath+"/account/Maintenance.html\">Maintenance</a></li>");                          
document.write(" 	 				</ul>");                            
document.write(" 	 			</li>");                          
document.write(" 	 		</ul>");                                
document.write(" 	    </div>");                               
document.write(" 	</div>");  
document.write("</div>");  